### ISSUE TITLE
Ошибка при открытии сайта с своего приложения

### ISSUE THREAD

**Issue by FUAll228** [elyby/accounts-frontend#22]
Создаю проект в VisualStudio
Запускаю в WebBrowser с ссылкой ваш сайт(если точнее account.ely.by) и вылетает ошибка 
![N6rnD0m11Lo](https://user-images.githubusercontent.com/33398458/79071520-d53aa700-7ce4-11ea-997e-62efa5c9aa37.jpg)

Ссылка из ошибки https://account.ely.by/vendors.js?fe0eeecec2c0ab9236dc

В обычных браузерах (chrome, IE) запускается нормально

Из того, что происходит в самом объекте WebBrowser, вечно крутится кубик, дальше не заходит
![x2U8DwVHqNE](https://user-images.githubusercontent.com/33398458/79071527-dff53c00-7ce4-11ea-8281-9bed678ccbef.jpg)
При любом выборе, в окне ошибки, продолжать сценарии или нет, так и так дальше загрузочного окна не зайдет

**Comment by erickskrauch** [comment]
Привет. Насколько мне известно, Visual Studio под капотом использует движок IE. И, вероятно, не тот же, что используется системой. Попробуй открыть в браузере, собираемом силами VS, сайт https://www.whatismybrowser.com. Он даст информацию о том, что за браузер используется и какова его версия.

**Comment by FUAll228** [comment]
![image](https://user-images.githubusercontent.com/33398458/79073031-e4255780-7cec-11ea-8b81-381f9f1b0a99.png)
И что делать ?

**Comment by erickskrauch** [comment]
Боюсь, с этим ничего особо не сделаешь. Мы можем добавить `meta` заголовок, который, по идее, должен будет сказать браузеру не использовать режим совместимости, но даже в IE11 мы уже не можем обеспечить лучший опыт взаимодействия с сайтом, какой доступен в более современных браузерах.

Я рекомендую не использовать встроенный браузер вовсе (если это, конечно, не браузер на основе Chrome), а посылать системный сигнал на открытие ссылки, чтобы открывался браузер по-умолчанию и пользователь выполнял действия в нём. Это также ускорит процесс авторизации, т.к. пользователю не нужно будет заново вводить свои учётные данные.

Перед открытием браузера, необходимо поднять локальный веб-сервер на случайном порту и указать в качестве `redirect_uri` значение `localhost:1234`, где `1234` — порт, на котором слушает веб-сервер. Пользователь завершит процесс авторизации и передаст на указанный адрес (т.е. локальный веб-сервер) auth code, по которому ты сможешь завершить процесс авторизации согласно документации. После успешной авторизации, с веб-сервера можно вернуть редирект на `https://account.ely.by/oauth2/code/success?appName=yourAppName`, т.к. закрыть вкладку в современных браузерах нельзя.

Такой сценарий авторизации используется в TL. Мой косяк, что это не задокументировано. Постараюсь исправить это в ближайшее время.
