### ISSUE TITLE
Счётчик друзей

### ISSUE THREAD

**Issue by Ponywka** [elyby/accounts-frontend#35]
При непредвиденных обстоятельствах (случайности) происходят странности со счётчиком друзей
Просто тыкаясь по страницам можно получить случайное число друзей, хотя например лично у меня их на Ely.by нет.
(а зачем система друзей на Ely.by?)

![firefox_1KdkHpLMZF](https://user-images.githubusercontent.com/26777464/162252187-1525248b-df79-47a8-949f-f9c53e6afbac.png)

**Comment by erickskrauch** [comment]
Хм, действительно. У меня на этой странице тоже отображается 59 друзей. Вероятнее всего, неправильно берётся контекст источника друзей. Проверю.

**Comment by erickskrauch** [comment]
Исправлено. Спасибо за issue!
