### ISSUE TITLE
Website not loading skins and acting slow

### ISSUE THREAD

**Issue by lemonzest79** [elyby/accounts-frontend#39]
Website is taking ages to load anything today (06-10-2024) I'm in the UK

https://ely.by/skins/s1893810

![Screenshot from 2024-10-06 15-20-20](https://github.com/user-attachments/assets/f4106327-c544-45bf-b0e6-1db306c67bd2)

**Comment by erickskrauch** [comment]
The issue has been resolved. Sorry for inconvenience.
